name: deploy

# masterブランチにpushしたときのみ実行
on:
  push:
    branches:
      - main

env:
  DEPLOY_TARGET: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: '24.9.0'
        cache: npm
    - run: |
        npm ci
        mkdir -p dist
        cd dist
        npx mmdc -i ../sample1.md -o sample1.md
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
