name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/configure-pages@v5
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: '24.9.0'
        cache: npm
    - run: npm ci
    - run: make
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
